name: dump

on:
  repository_dispatch:
    types:
      - dump-from-toolbox
      - dump-from-vulkan.zig
      - dump-from-wayland.zig
      - dump-from-X11.zig
      - dump-from-glfw.zig
      - dump-from-cimgui.zig
      - dump-from-spirv.zig
      - dump-from-glslang.zig
      - dump-from-shaderc.zig
      - dump-from-spaceporn
      - dump-from-spaceporn-action-env
      - dump-from-spaceporn-action-bot
      - dump-from-spaceporn-action-ci
      - dump-from-spaceporn-action-cd-ping
      - dump-from-spaceporn-action-cd-pong

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump client_payload
        env:
          CLIENT_PAYLOAD: "${{ toJson(github.event.client_payload) }}"
        run: |
          printf '%s\n' "${CLIENT_PAYLOAD}"

      - uses: tiawl/spaceporn-action-env@v1.0.3

      - name: Check client payload tag field and repository
        uses: actions/checkout@v4
        with:
          repository: "${{ github.repository_owner }}/${{ github.event.client_payload.from }}"
          ref: "${{ github.event.client_payload.tag }}"

      - name: Does it needs zig ?
        id: zig
        shell: bash
        run: |
          if [[ -f "${GITHUB_WORKSPACE}/build.zig" ]]
          then
            printf 'needed=true\n' >> "${GITHUB_OUTPUT}"
          else
            printf 'needed=false\n' >> "${GITHUB_OUTPUT}"
          fi

      - uses: mlugg/setup-zig@v1
        if: steps.zig.outputs.needed == 'true'
        with:
          version: ${{ env.zig_version }}

      - name: Check client payload hash field
        env:
          PAYLOAD_HASH: "${{ github.event.client_payload.hash }}"
          URL: "${{ github.server_url }}/${{ github.repository_owner }}/${{ github.event.client_payload.from }}/archive/refs/tags/${{ github.event.client_payload.tag }}.tar.gz"
          ZIG: "${{ steps.zig.outputs.needed }}"
        shell: bash
        run: |
          if [[ "${ZIG}" == 'true' ]]
          then
            [[ "${PAYLOAD_HASH}" == "$(zig fetch "${URL}")" ]]
          else
            [[ -z "${PAYLOAD_HASH}" ]]
          fi
